#this is repitative configation property in all microservice.
# spring:
#   application:
#     name: config-default
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8778/eureka  #eureka endpoint
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
