#this is repitative configation property in all microservice.
spring:
  application:
    name: config-prod
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #eureka endpoint
