#this is repitative configation property in all microservice.
# spring:
#   application:
#     name: config-default

spring:
    # Configure the message broker connection (RabbitMQ or Kafka)
  cloud:
    config:
      uri: http://${CONFIG_SERVER_SERVICE_SERVICE_HOST:localhost}:8085
    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
  rabbitmq:
    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:50790/eureka #eureka default port = 8761
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
